# syntax = docker/dockerfile:1
ARG NODE_VERSION=18
FROM node:${NODE_VERSION}-slim as base

ENV NODE_ENV=development
WORKDIR /src

# Build
FROM base as build
COPY package.json package-lock.json ./
RUN npm install

# Run
FROM base
CMD [ "npm", "run", "dev" ]

